@extends('layouts.adminapp')
@section('content')
<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>

<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>
<h1>EU QUE SOU O ADMIN,PORRA!</h1>

@stop
